### ISSUE TITLE
Single Downloader?

### ISSUE THREAD

**Issue by maxdoutex** [wizzomafizzo/mrext#1]
Hope I didn't overlook it but have you considered making a single downloader for the downloader.ini that will grab all of your utilities?

**Comment by wizzomafizzo** [comment]
I definitely want to do that! I was thinking about it for a while but wasn't sure if there would be a demand for it. I'll bump it up the list. Thanks for suggesting it

**Comment by theypsilon** [comment]
That sounds like a great idea. If you like, I'd be up for adding that DB to the Settings Screen of Update All.

**Comment by wizzomafizzo** [comment]
@theypsilon ok done! Here's the file

```
[mrext/all]
db_url = https://github.com/wizzomafizzo/mrext/raw/main/releases/all.json
```

@maxdoutex and you can use this now too!
