### ISSUE TITLE
LaunchSync not compatible with the new “mgl” cores.

### ISSUE THREAD

**Issue by thiagoauler** [wizzomafizzo/mrext#10]
Some time ago, MiSTer was updated to have a more organized structure. There are some cores that implements functionality for multiple systems (i.e. SMS implements Gamegear system and ATARI7800 implements Atari 2600 system).
The way it works is simple: a new “mgl” file is created for this secondary systems, and the auxiliary files and ROMs goes to the new directory.
In this new MiSTer setup, Atari 2600 games are now stored in the Atari2600 folder… and the launchsync is not prepared to read these new folders. (This issue happens to a lot more systems)

**Comment by wizzomafizzo** [comment]
Sorry for the wait. I've been working on a solution to this that's about 90% there. Just nutting out some last bugs and then I can put up a new launchsync release

**Comment by wizzomafizzo** [comment]
@thiagoauler Hi mate. I just put up a new release of launchsync that should implement all the new mgl files. Could you please give it a shot and let me know how it goes :)

**Comment by wizzomafizzo** [comment]
Let me know if it didn't work past your initial tests!
