### ISSUE TITLE
Error message at first launch

### ISSUE THREAD

**Issue by Xavier-SD** [wizzomafizzo/mrext#14]
/tmp/script: line 5: 1905 illegal instruction    /media/fat/Scripts/remote.sh

**Comment by wizzomafizzo** [comment]
This is very unusual, I've never seen it before!

Would it be possible for you to upload a copy of the remote.sh file that's on your mister so I could try it too?

And after you get that, it may be worth trying to re-download it from here and copy it over again. I wonder if there's been some corruption of the file

**Comment by wizzomafizzo** [comment]
Finally someone else had this issue. I'm guessing you sorted this out, but, please set FileZilla to upload in binary mode.

https://www.oryon.net/knowledge-base/article/how-to-change-filezilla-ftp-program-to-binary-transfer/

The .sh extension confuses it and makes it thinks it's a text file.
