### ISSUE TITLE
Sub folders with launchsync

### ISSUE THREAD

**Issue by calle81** [wizzomafizzo/mrext#15]
Hi, I would love if it was possible to recreate the best of list from the htgdb gamepacks.

However we need the ability to recreate the folder structure
Example:
/media/fat/games/SNES/4 Game Series Collections/Best-Of Lists/7 Great Non-US Games - Destructoid.com
To:
/media/fat/_Playlists/SNES/Game Series Collections/Best-Of Lists/7 Great Non-US Games - Destructoid.com

So in this case the _playlist folder would need to have a similar subfolder structure as games.

Doing some tests with: https://github.com/calle81/mister_playlists

**Comment by calle81** [comment]
https://github.com/calle81/mister_playlists

**Comment by wizzomafizzo** [comment]
Hi! Sorry, I didn't see this come in. Try it! I'm pretty sure I added in that you can do subfolders, just put a forward slash in the name. [folder1/folder2/stuff]

Let me know if it's not working for you though!
