### ISSUE TITLE
Error when executing remote.sh

### ISSUE THREAD

**Issue by PanterACFH** [wizzomafizzo/mrext#16]
Issue with the remote script.
When I run it, I get this message on the screen:

Error adding to startup: Failed to create a new window
Error displaying service info: Failed to create a new window
Press any key to continue

I have added the lines in to downloader.ini and enabled the the MiSTer Extensions repository in the Unofficial Scripts submenu

**Comment by wizzomafizzo** [comment]
Hi mate. Sounds like the app can't create the admin gui on your setup. Are you using a CRT? And do you have this problem with other scripts like the official ini_settings one? You can also try run it over SSH, you only really need to run it manually one time

If that doesn't work, I'll add in a workaround so it just does a basic text gui if the normal one fails to launch

**Comment by PanterACFH** [comment]
Yes, I am using a Sony Trinitron CRT.
No issues running the official ini_settings one.
I see some writing flash up on the screen quickly, like it does with your Remote. Then ini_settings loads up a new screen (like the update all settings page), although it doesn't fit on the screen properly and wraps around.
I have attached a small video, showing the loading attempt of remote, and the loading of ini_settings.

https://github.com/wizzomafizzo/mrext/assets/13247385/cd022c9c-4860-4b7e-a9da-90ffe62bd443

Cheers mate.

**Comment by PanterACFH** [comment]
Yep, just did the telnet thing and ran the script.
Rebooted the DE-10 and yep, it is still working.
Thank you for your help and sorry to bother you at work.
Cheers
Matt

**Comment by wizzomafizzo** [comment]
No problem at all! Glad it's working and thank you for reporting

I'll keep the issue open until I implement the other workaround so I don't forget :)

**Comment by wizzomafizzo** [comment]
Added fallback non-curses interface if curses launch fails.
