### ISSUE TITLE
install from downloader failed

### ISSUE THREAD

**Issue by Schermobianco** [wizzomafizzo/mrext#2]
hi @wizzomafizzo, today i tried to install all your script but the downloader failled, attached you can find the .log file and the downloader.ini

can you help me? Thanks Man

[downloader1.log](https://github.com/wizzomafizzo/mrext/files/9594310/downloader1.log)
[downloader.ini.txt](https://github.com/wizzomafizzo/mrext/files/9594317/downloader.ini.txt)

**Comment by wizzomafizzo** [comment]
Hi. Thanks for reporting this. Can you please give it another shot? Should be ok now. Silly mistake I made with the update files

**Comment by Schermobianco** [comment]
now is working! thanks again

**Comment by wizzomafizzo** [comment]
No worries!
