### ISSUE TITLE
The main directional buttons on the "Control" page are not working. 

### ISSUE THREAD

**Issue by saboten99** [wizzomafizzo/mrext#29]
After the last update, the main light purple directional control buttons do not work. The "OK" button and other buttons on the control page work, but the 4 main ones representing left, right, up and down do not work.

**Comment by wizzomafizzo** [comment]
Thank you for reporting this! It's weird that it only came up in the last update, but I think I've tracked the issue down. I will release an update later today :)

**Comment by wizzomafizzo** [comment]
You can try this out: https://www.dropbox.com/scl/fi/051gwpnyc92vvirunqb6w/remote-0.2.2beta.zip?rlkey=vk59hpwbqnbhrejlns5nivxof&dl=0

I will do a release later today or so. Depends when I can get another issue fixed.

**Comment by saboten99** [comment]
Looks like its fixed to me. Thanks Wizzo.
