### ISSUE TITLE
Remote keyboard key's missing

### ISSUE THREAD

**Issue by Retroperator** [wizzomafizzo/mrext#31]
Hi!

First of all thanks for the great script for the MiSTer! It's really awesome!

Lot's of computer core's need some special key like an F-key or Esc to start or quit a game. Would it be possible to add these to the keyboard of the Remote script?

**Comment by wizzomafizzo** [comment]
Hi mate. Thank you! Glad to hear you're liking it.

You can access these keys now. If you open the virtual keyboard on the control page, then press the 123 button in the bottom left, then the FN~ key above it. I basically copied how they do it on an Android keyboard.

You are not the first person to ask this. Is there anything I can do to make it more intuitive? In the future I plan to make the buttons react to what core is open, so let's say a computer core is open I can show the F keys straight on the page or a special F keys button.

**Comment by Retroperator** [comment]
Ah.. I missed that.. I pressed the 123 and associated FN~ with the FN-key on a laptop so i did not press it..

So to make it more intuitive i would call it Func for functionkeys.. Just to make the distinction from the FN-key on laptops.

Furthermore you could put this on the fist page next to the 123-button so you don't have to press two buttons to get where you want to be and to massage people to check what this unknown Func-button does..

A future core specific keyboard would be a killer feature! I would love to see all the keys available on the original machine!
You could also expand this feature to show keypads on some controllers like, for instance, the atari 5200-controller..

Anyway.. Thanks for this awesome project and the quick response!

**Comment by wizzomafizzo** [comment]
I'm not sure if I released it yet but I put this in now with the new key names. I actually just noticed the coloured buttons idea, I like that a lot. Probably pop that in too!

**Comment by Retroperator** [comment]
Glad to hear that my comments are helpful.
I just checked and you've not yet released the changes.. Please take your time and release when you want to..

Thanks again for your work\time.. Much appreciated!
