### ISSUE TITLE
nfc.sh seems to be in an incorrect encoding

### ISSUE THREAD

**Issue by wolfshow** [wizzomafizzo/mrext#34]
After opening up the file, I can only see messy code there. Does anyone have the same issue?

**Comment by wizzomafizzo** [comment]
Hi. That's normal. The file is not actually a shell script, it's a compiled binary. It's just called .sh so mister will show it in the scripts menu

You can take a look at the source here:
https://github.com/wizzomafizzo/mrext/tree/main/cmd%2Fnfc

**Comment by wolfshow** [comment]
Thanks!

**Comment by wolfshow** [comment]
> @wizzomafizzo, I followed the steps in readme and added a new text record and write text into a tag. But mister has no response using NFC (only beep several times). Any possible problems I need to check?

Just look at the code, should be fail.wav

**Comment by wolfshow** [comment]
![image](https://github.com/wizzomafizzo/mrext/assets/3775235/bb9b4405-289f-4722-b804-07d3fd03a4af)

**Comment by wizzomafizzo** [comment]
Hi mate. The card is written correctly but at the moment the script doesn't support mifar cards, only ntag213 to 216 cards

I do have some mifare 1k cards though and I think it should just be a configuration thing. Let me see if I can add support

**Comment by wolfshow** [comment]
> Hi mate. The card is written correctly but at the moment the script doesn't support mifar cards, only ntag213 to 216 cards
> 
> I do have some mifare 1k cards though and I think it should just be a configuration thing. Let me see if I can add support

thanks for the great efforts!
