### ISSUE TITLE
I have some tools, I don't know if you want to put them here

### ISSUE THREAD

**Issue by sigboe** [wizzomafizzo/mrext#5]
I have, well of tools that are shippable, I have two. I don't know if you are interested in them, but i if you are, here:

### RSS feed on the wallpaper
https://github.com/sigboe/MiSTress 
This one works quite well for me, I use it, its not perfect, but its quite useful

### remote control the keyboard of the MiSTer
https://github.com/sigboe/reMiSTer
This one is less polished, it has some issues, but there has been situations it has been quite useful

**Comment by wizzomafizzo** [comment]
Absolutely! I've added them to the list. The wallpaper RSS feed is really clever, I never thought of using all that empty space like that. It's a shame we can't update the wallpaper without reloading the core
