### ISSUE TITLE
Folder Support with launchsync

### ISSUE THREAD

**Issue by thiagoauler** [wizzomafizzo/mrext#6]
I began using launchesync to create my own playlists.
The one feature I'm missing the most is the ability to use folders.
My suggestion would be having a 'folder = ' variable to set it.
For example:

name=My List of Games
...

[Game 1]
system = ...
folder = Category A
match = ...

[Game 2]
system = ...
folder = Category B
match = ...

[Game 3]
system = ...
folder = Category A
match = ...

Would end up with this structure:
- My List of Games
   - Category A
     -  Game 1
     - Game 3
   - Category B
      - Game 2

**Comment by wizzomafizzo** [comment]
I think this is a great idea. I do need some feedback though, originally when I was thinking about this a little, I was going to implement it so the folder was part of the shortcut name in the square brackets. For example:

[Category A/Game 1]
...

[Category B/Game 2]
...

And so on. What are your thoughts on this method? I could go either way really. I like the folder attribute as well, it looks nice and clean, and it will be a little easier to implement. I thought the square bracket method might be more intuitive though.

I will also need to do some tests. launchsync uses a standard ini parser, and I'm not sure how it will react to duplicate section names. So 2 games with the same name but in different folders may be a problem with the folder attribute method.

**Comment by thiagoauler** [comment]
That makes total sense!
If section names should be unique, maybe the better way to go is [custom/folder/game].

**Comment by wizzomafizzo** [comment]
> That makes total sense! If section names should be unique, maybe the better way to go is [custom/folder/game].

I have just put up a new release of LaunchSync which includes this new feature. I did end up going with the [custom/folder/game] style instead. I think it came out looking pretty good though!

Can you please give it a test and let me know how it goes. It ended up being a pretty significant change, I'm not sure I quite caught everything.

**Comment by thiagoauler** [comment]
Thank you…
I will test it over the weekend!

**Comment by thiagoauler** [comment]
Just tested the new feature!!! It is working great.. Even sub-folders are being created correctly! 
Now, it’s possible to create a more “elaborated” playlist with a single sync file.

Thanks a lot!

**Comment by thiagoauler** [comment]
Just tested the new feature!!! It is working great.. Even sub-folders are being created correctly!
Now, it’s possible to create a more “elaborated” playlist with a single sync file.

Thanks a lot!
