### ISSUE TITLE
nfc.csv broken on latest release

### ISSUE THREAD

**Issue by Alcedes28** [wizzomafizzo/mrext#61]
Existing nfc.csv file no longer works using latest release. Using mifare cards and statically defining them using nfc.csv file.
Rolling back to the previous version of nfc.sh allows it to work again.

**Comment by retrob0t** [comment]
Having the same issue here, nfc.csv suddenly stopped working after script update (using NFC215 cards).

As an example:

**match_uid,match_text,text
0447dc66100289,,SNES/- RACING/Super Mario Kart (Japan).sfc**

It finds the UID no problem (matching the defined UID in the .csv file) but gives the following error:

> WARN no text NDEF found
> launching with uid match override
> ERR error launching card: no text NDEF found in card or database

**Comment by wizzomafizzo** [comment]
sorry about that! i'll get this fixed up again soon

**Comment by sigboe** [comment]
Can this issue be closed?
