### ISSUE TITLE
Support for NTAG203

### ISSUE THREAD

**Issue by djEatch** [wizzomafizzo/mrext#65]
Hi, would there be any chance that NTAG203 could be supported (to allow LEGO dimensions characters to be used)?
Personally don't mind if support is via CSV only.
Thank you.

**Comment by symm** [comment]
Hi @djEatch I have an NTAG203 card and tested working okay (functionally the same as a NTAG213). Did you get an error when scanning the dimensions character?

**Comment by djEatch** [comment]
I got an RF transmission error (but it did
show the cards ID, it just didn't pass it through to the fields at the top of the page).
It was the first type I tried, so I thought I might have a clone reader... but it worked fine with 213, 215, 216 and amiibo, so assumed it just wasn't supported.
It works in nfc app on android, and using the reader in Windows, which should rule out afaulty chip or reader?

-------- Original message --------
From: Gareth Jones ***@***.***>
Date: 28/09/2023 23:03 (GMT+00:00)
To: wizzomafizzo/mrext ***@***.***>
Cc: djEatch ***@***.***>, Mention ***@***.***>
Subject: Re: [wizzomafizzo/mrext] Support for NTAG203 (Issue #65)


Hi @djEatch<https://github.com/djEatch> I have an NTAG203 card and tested working okay (functionally the same as a NTAG213). Did you get an error when scanning the dimensions character?

**Comment by symm** [comment]
Cool, after a bit of searching[[1]](http://www.proxmark.org/forum/viewtopic.php?id=2657) it looks like the Lego Dimensions have the lock bits set[[2]](https://www.nxp.com/docs/en/data-sheet/NTAG213_215_216.pdf#page=13). This prevents reading certain blocks on the tag unless a password is provided first (throwing RF transmission error).

This will need some code changes to get it working, a couple of ideas:

1. If password / lock bits are set skip reading all together and fallback to csv
2. If RF transmission error occurs, fallback to csv
