### ISSUE TITLE
Resetting search db

### ISSUE THREAD

**Issue by dpan** [wizzomafizzo/mrext#7]
Hi, I want to reset the search db, but can't find search.db file anywhere

**Comment by wizzomafizzo** [comment]
Hi! It's possible I updated the documentation but didn't update a new version of search with the change. If there is a file on your SD card called index.db or index.tar you can delete that instead. It will be called search.db in the next update.

**Comment by dpan** [comment]
it was index.tar. Deleted it and db was reset. Thank you!
