### ISSUE TITLE
Way to hide MacOS folder metadata in Games browser?

### ISSUE THREAD

**Issue by Arkaium** [wizzomafizzo/mrext#85]
First off I think the app is amazing, I can’t believe how much functionality it has, launching a game from just a few finger taps is wild to me.

I did notice though, since my MiSTer’s SSD was loaded up using a Mac, that all the hidden MacOS metadata folders show up first (image attached), these are the ones with “._” at the start of the folder name.

Would it be possible to hide these folders, either with a simple folder name search that would quash any folder that starts with “._” or some other way? It makes the Games nav option somewhat challenging for me and while I could delete the folders, any time I reconnect the SSD they’ll be back.

Thank you!

![image](https://github.com/wizzomafizzo/mrext/assets/104634089/31a9f0eb-dd93-473f-af7f-8b3ede150cbb)

**Comment by wizzomafizzo** [comment]
Sure thing! Will be in the next release. I'm glad to hear you're enjoying it too :)
