### ISSUE TITLE
Please add 8x10 option to the TapTo Designer web app

### ISSUE THREAD

**Issue by sbugliarisi** [wizzomafizzo/mrext#89]
The TapTo Designer web app has options for A4 and Letter, it would be great if it could also support 8x10. Requesting this as Shutterfly doesn't offer A4 or Letter size printing :(

**Comment by asturur** [comment]
hi @sbugliarisi , the correct issue tracker for the tapto deisgner app is
https://github.com/asturur/nfc-retro-label-printer/issues

Also please specify if this format is already precut or is just a full sheet of paper were we need to fit as much labels as possible

**Comment by sbugliarisi** [comment]
Thank you! I added an issue to the other location. I’ll close this one
